### ISSUE TITLE
Doesn't work for Flutter Web, fails with XMLHttpRequest error

### ISSUE THREAD

**Issue by Anmol92verma** [jg-l/metadata_fetch#26]
Stack Trace
 
` Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 71:22                                       <fn>
dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 704:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 733:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>

    at Object.createErrorWithStack (http://localhost:53250/dart_sdk.js:5348:12)
    at Object._rethrow (http://localhost:53250/dart_sdk.js:39350:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53250/dart_sdk.js:39344:13)
    at Object._microtaskLoop (http://localhost:53250/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:53250/dart_sdk.js:39182:13)
    at http://localhost:53250/dart_sdk.js:34689:9`

I tried to run the sample code and it fails, Is this a known bug ?

**Comment by caseyryan** [comment]
The same issue here. I've seen a lot of topic where people say it's because CORS headers not being sent from a backend. I can testify it has nothing to do with CORS since I'm testing in on our dev backend that works fine with React on the same host but not with Flutter Web and I'm totally sure the backend sets "Access-Control-Allow-Origin: *". The issue is 100% related to the way Dart works with http in browsers.

**Comment by ziadshebl** [comment]
Same issue happened to me, is there any workaround or solution?

**Comment by caseyryan** [comment]
Your backend must have an endpoint that accepts OPTIONS request (it's called a Preflight request) and send response with status code 204 to it. Literally if you request GET https://example.com/users/profile a browser will first try to do it with OPTIONS https://example.com/users/profile and when it gets 204 then it will try GET. Make sure your backend can process it

**Comment by Anmol92verma** [comment]
Then why does it work with flutter mobile ?

**Comment by caseyryan** [comment]
Because Flutter mobile is not a browser. Only web browsers send Preflight requests

**Comment by mirrorlink** [comment]
this solves the issue for testing locally

https://stackoverflow.com/questions/65630743/how-to-solve-flutter-web-api-cors-error-only-with-dart-code

**Comment by ollydixon** [comment]
I would close this issue, it's not related to this package. It's just a simple Cors issue.

**Comment by ollydixon** [comment]
I have the same issue, and we are going across sites to fetch meta data. For example, if someone posts a YouTube link. How can we get around this?
